### ISSUE TITLE
Compiling on mac

### ISSUE THREAD

**Issue by SemiQuant** [EvolBioInf/mirth#1]
Hi, I get the following error when I try make on mac os. No issues when I use linux though. 

`c++ -std=c++11 -Isrc -Wall -Wextra -O3 -g -ggdb -Wshadow  -Ilibdivsufsort/include -c -o src/args.o src/args.cpp
c++ -std=c++11 -Isrc -Wall -Wextra -O3 -g -ggdb -Wshadow  -Ilibdivsufsort/include -c -o src/bench.o src/bench.cpp
c++ -std=c++11 -Isrc -Wall -Wextra -O3 -g -ggdb -Wshadow  -Ilibdivsufsort/include -c -o src/esa.o src/esa.cpp
c++ -std=c++11 -Isrc -Wall -Wextra -O3 -g -ggdb -Wshadow  -Ilibdivsufsort/include -c -o src/fastafile.o src/fastafile.cpp
c++ -std=c++11 -Isrc -Wall -Wextra -O3 -g -ggdb -Wshadow  -Ilibdivsufsort/include -c -o src/mirth.o src/mirth.cpp
c++ -std=c++11 -Isrc -Wall -Wextra -O3 -g -ggdb -Wshadow  -Ilibdivsufsort/include -c -o src/pfasta.o src/pfasta.cpp
c++ -std=c++11 -Isrc -Wall -Wextra -O3 -g -ggdb -Wshadow  -Ilibdivsufsort/include -c -o src/util.o src/util.cpp
src/util.cpp:156:82: error: use of undeclared identifier 'MAP_POPULATE'
  char* data = reinterpret_cast<char*>(mmap(NULL, r.sz, PROT_READ, MAP_PRIVATE | MAP_POPULATE, fd, 0));
                                                                                 ^
1 error generated.
make: *** [src/util.o] Error 1`

**Comment by kloetzl** [comment]
As far as I can tell, the whole `with_mmap` function is not needed and you can safely delete it and try again. That should solve the issue until @apirogov finds a proper solution.

Thanks for reporting.

**Comment by SemiQuant** [comment]
Thanks @kloetzl. That worked, runs fine.
